ALTER TABLE public.clientes DROP COLUMN endereco_estado;
ALTER TABLE public.clientes ADD estado_id int8 NULL;

CREATE TABLE public.estados (
	id int8 NOT NULL GENERATED BY DEFAULT AS identity,
	nome varchar(120) NOT NULL,
	CONSTRAINT estados_pkey PRIMARY KEY (id)
);

ALTER TABLE public.clientes ADD CONSTRAINT clientes_fk FOREIGN KEY (estado_id) REFERENCES public.estados(id);